<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_aqui</name>
   <tag></tag>
   <elementGuidId>809f587a-fdf9-4225-9637-c64d2c043e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'aqui')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.ng-star-inserted > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;aqui&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>82beba28-1995-460e-8779-3ae77adc651b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bookings</value>
      <webElementGuid>0203dd56-fd8c-4bc1-8dc1-a608f050aae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>aqui</value>
      <webElementGuid>1f9a62de-fe85-4f68-82a4-a7116c9ab404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[1]/div[@class=&quot;container-fluid d-flex flex-grow-1&quot;]/app-transaction-handler[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-flex justify-content-center align-items-center w-100 mt-2 mb-5&quot;]/div[@class=&quot;mb-1 ng-star-inserted&quot;]/app-payment[1]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container mt-4&quot;]/div[@class=&quot;card text-center&quot;]/div[@class=&quot;card-body&quot;]/h5[@class=&quot;ng-star-inserted&quot;]/a[1]</value>
      <webElementGuid>549082a8-8a4d-4a9d-990b-a001d082764d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'aqui')]</value>
      <webElementGuid>c995ac1f-73da-4424-9427-88fef4152078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A sua reserva está confirmada!'])[1]/following::a[1]</value>
      <webElementGuid>5877282e-c3aa-4547-9737-1b0764bf525d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='aqui']/parent::*</value>
      <webElementGuid>09ffde96-d9af-4d4e-9616-7246f6a5c7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/bookings')])[3]</value>
      <webElementGuid>d257836e-86d0-4cfd-9394-235513320416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5[3]/a</value>
      <webElementGuid>c77438b0-1518-41a4-9f1b-b89d9fe21afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/bookings' and (text() = 'aqui' or . = 'aqui')]</value>
      <webElementGuid>6800d4d1-b318-4d28-8a1a-b1ede23bef37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
