<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reservar</name>
   <tag></tag>
   <elementGuidId>277de477-5e2d-4c0e-a8cc-c6585b9ae653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Hóspedes'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-success.mt-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Reservar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66649cef-3675-48ff-bba2-9f093d1768f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success mt-1</value>
      <webElementGuid>9140dbc2-e91c-4fd5-beee-8a93b8a08171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reservar</value>
      <webElementGuid>285bd553-d786-49c2-bbb3-a422a01b2df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[1]/div[@class=&quot;container-fluid d-flex flex-grow-1&quot;]/app-property-ad-retrieve[1]/div[@class=&quot;main d-flex flex-column w-100&quot;]/div[@class=&quot;d-flex mt-5 mb-5 gap-5 ms-5 me-5&quot;]/div[@class=&quot;reservar p-3 border border-secondary rounded d-flex text-center&quot;]/form[@class=&quot;form center-form d-flex flex-column align-items-center flex-grow-1 mb-4 ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;d-flex flex-column justify-content-around gap-3&quot;]/button[@class=&quot;btn btn-success mt-1&quot;]</value>
      <webElementGuid>064e9953-7576-4062-8015-33fde8b4bf65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hóspedes'])[1]/following::button[1]</value>
      <webElementGuid>80e35799-511d-4d2e-bb40-81acfcd4d3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='–'])[1]/following::button[2]</value>
      <webElementGuid>d74734bc-f7b1-438f-9733-236ff4ebb98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ainda não vai ser cobrado'])[1]/preceding::button[1]</value>
      <webElementGuid>3238ebff-5514-4dbe-a60a-b8f6cfc13dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Taxa de Limpeza - 25€'])[1]/preceding::button[1]</value>
      <webElementGuid>d34d06e2-5d9a-47b3-ab9b-cde73e0dd263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reservar']/parent::*</value>
      <webElementGuid>4a1ed4ef-fe2f-4998-899f-a5df9d5c9e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>3bba3ed6-61e0-49b2-999c-ba424448580f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Reservar' or . = 'Reservar')]</value>
      <webElementGuid>73de7f6a-c4cb-4db7-94d8-812dcedd6776</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
