<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Logout_w-100 h-100 rounded-3</name>
   <tag></tag>
   <elementGuidId>8eb9a124-42e4-4703-b03d-b0271217f460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://bookingbuddyrepository.blob.core.windows.net/images/propriedade-teste.png')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-100.h-100.rounded-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>app-homepage-property >> internal:has-text=&quot;Propriedade 79265095560€ noitecompare_arrows&quot;i >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>61532d68-3075-4380-bbda-b58b39cea928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 h-100 rounded-3</value>
      <webElementGuid>22d48ffa-a2ba-4724-9865-d1a04eca7c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bookingbuddyrepository.blob.core.windows.net/images/propriedade-teste.png</value>
      <webElementGuid>e68bcf13-37ef-46a1-a62a-1a807e998cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[1]/div[@class=&quot;container-fluid d-flex flex-grow-1&quot;]/app-homepage[1]/div[@class=&quot;d-flex p-3 w-100 flex-row flex-wrap align-content-start justify-content-start&quot;]/app-homepage-property[1]/div[@class=&quot;property d-flex flex-column p-3 w-100 h-100&quot;]/a[@class=&quot;w-100 h-75 m-1&quot;]/img[@class=&quot;w-100 h-100 rounded-3&quot;]</value>
      <webElementGuid>aac0a7b5-0edc-43c8-9178-3d1db6c9b3d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bookingbuddyrepository.blob.core.windows.net/images/propriedade-teste.png')]</value>
      <webElementGuid>5ec148ac-dedd-43e0-baeb-164ff18adedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-homepage-property/div/a/img</value>
      <webElementGuid>d4c11561-dbd8-49a1-b577-b9b90a1eeabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bookingbuddyrepository.blob.core.windows.net/images/propriedade-teste.png']</value>
      <webElementGuid>062df84a-add6-4bd1-ad69-f1c95924d4d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
