<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__mat-mdc-button-touch-target</name>
   <tag></tag>
   <elementGuidId>e3bad21c-176d-495a-855f-56f18a718ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-mdc-button-touch-target</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open calendar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0477567-084f-4bea-895e-aeb6c945a753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-button-touch-target</value>
      <webElementGuid>4ede97d6-0aa9-4283-8208-ef76334b5f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[1]/div[@class=&quot;container-fluid d-flex flex-grow-1&quot;]/app-property-ad-retrieve[1]/div[@class=&quot;main d-flex flex-column w-100&quot;]/div[@class=&quot;d-flex mt-5 mb-5 gap-5 ms-5 me-5&quot;]/div[@class=&quot;reservar p-3 border border-secondary rounded d-flex text-center&quot;]/form[@class=&quot;form center-form d-flex flex-column align-items-center flex-grow-1 mb-4 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;d-flex flex-column justify-content-around gap-3&quot;]/mat-form-field[@class=&quot;mat-mdc-form-field mat-mdc-form-field-type-mat-date-range-input mat-mdc-form-field-has-icon-suffix mat-form-field-appearance-fill mat-form-field-hide-placeholder mat-primary ng-tns-c2608167813-0&quot;]/div[@class=&quot;mat-mdc-text-field-wrapper mdc-text-field mdc-text-field--filled&quot;]/div[@class=&quot;mat-mdc-form-field-flex&quot;]/div[@class=&quot;mat-mdc-form-field-icon-suffix&quot;]/mat-datepicker-toggle[@class=&quot;mat-datepicker-toggle&quot;]/button[@class=&quot;mdc-icon-button mat-mdc-icon-button mat-unthemed mat-mdc-button-base cdk-focused cdk-mouse-focused&quot;]/span[@class=&quot;mat-mdc-button-touch-target&quot;]</value>
      <webElementGuid>ada43e34-5554-4c74-a141-d553a77ce6f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>4eb07a43-acb6-4aaf-8640-5ac869809fc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
