<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Iniciar sesso</name>
   <tag></tag>
   <elementGuidId>39a801a0-e13e-44f1-9e77-9c8c40a28b3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-login.mt-4.w-100.p-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Iniciar sessão&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>145311a1-da28-41f2-a03d-5b361f9c0e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1a8713b3-4d9a-440d-8216-6239ffb312df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-login mt-4 w-100 p-2</value>
      <webElementGuid>5b66750a-2ce9-4f1a-b904-a48d80a00615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iniciar sessão </value>
      <webElementGuid>ace34586-f36a-49c4-a2ce-3c795166dddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[@class=&quot;flex-grow-1 d-flex flex-column&quot;]/div[@class=&quot;container-fluid d-flex flex-grow-1&quot;]/app-signin-component[1]/div[@class=&quot;d-flex w-100 flex-column align-items-center justify-content-between&quot;]/div[@class=&quot;d-flex flex-column align-items-center justify-content-center&quot;]/form[@class=&quot;d-flex mb-3 w-100 flex-column align-items-center ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;w-100 py-2 d-flex flex-column align-items-end&quot;]/button[@class=&quot;btn btn-login mt-4 w-100 p-2&quot;]</value>
      <webElementGuid>2c23102e-2687-4998-a0f8-e95c75e97a4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>f972a2d4-e23e-4a06-8351-1a8ded2b2b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Esqueceu se da palavra-passe?'])[1]/following::button[1]</value>
      <webElementGuid>5bdcc384-97fc-400c-805b-d8c45f5111cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O email é inválido!'])[1]/following::button[2]</value>
      <webElementGuid>34f52a97-3ed1-4238-b3e9-948ff4eaa4e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ou faça login com'])[1]/preceding::button[1]</value>
      <webElementGuid>813589c1-055e-406f-a262-888671bb20f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Iniciar sessão']/parent::*</value>
      <webElementGuid>f12c32ff-9cc8-4576-a9fe-c772beb0bde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>cf9d6c23-83b6-458f-bde2-e4c0b1f7e1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Iniciar sessão ' or . = 'Iniciar sessão ')]</value>
      <webElementGuid>80a99f74-1a0c-42a4-8b79-f723c8ea420a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
