<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preencher informaes sobre o grupo_members</name>
   <tag></tag>
   <elementGuidId>05878967-3d36-4d29-b038-53dbc28cf4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;members&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='members']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Introduza o email de um membro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e83d9cbe-5c92-4dc9-aadc-310d0f5ff020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44265149-fcd0-449b-9d68-2cd0b209b4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>members</value>
      <webElementGuid>d74026a5-f9ad-4cb2-b4ec-21b3a83b9e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Introduza o email de um membro</value>
      <webElementGuid>21c85cd9-381e-4bb5-af8e-089f8c679fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>fea3ccd5-521e-4152-9524-b54fd8428983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>28479003-a156-487b-8caa-a558ac97af85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>9a7f2d7e-3b2f-4ed4-98d6-5d5f0ce87a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[@class=&quot;flex-grow-1 d-flex flex-column&quot;]/div[@class=&quot;container-fluid d-flex flex-grow-1&quot;]/app-group-create[1]/div[@class=&quot;d-flex h-100 w-100 flex-column align-items-center&quot;]/app-group-members-step[1]/div[@class=&quot;d-flex flex-column align-items-center justify-content-start my-auto p-5 flex-grow-1&quot;]/form[@class=&quot;d-flex w-75 mt-3 h-50 flex-column align-items-center justify-content-center p5 ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;d-flex w-100 flex-column mb-3 flex-grow-1&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>2c279893-4806-4320-8b00-5da4e8e0b23b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='members']</value>
      <webElementGuid>4caac418-1341-4030-a2fb-b7430e9552f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-group-members-step/div/form/div/input</value>
      <webElementGuid>07acdb43-def6-441b-87a6-9df73e992728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'members' and @placeholder = 'Introduza o email de um membro']</value>
      <webElementGuid>a2ddb289-f11b-4f8c-95c2-c6ac3743fe4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
