<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Favoritos_bi bi-list</name>
   <tag></tag>
   <elementGuidId>e7a8ef41-21ac-48cd-a41e-60b7cad72a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbarDarkDropdownMenuLink']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>67425590-86ff-4834-953d-c7f8ad4f2b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-list</value>
      <webElementGuid>1ffe0b55-f8d2-4aac-968e-25519572d3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarDarkDropdownMenuLink&quot;)/i[@class=&quot;bi bi-list&quot;]</value>
      <webElementGuid>72c9989d-a771-470a-b078-bde920de5a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='navbarDarkDropdownMenuLink']/i</value>
      <webElementGuid>b01ee178-4987-4087-926b-e0e6a82caeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>34bdb002-930e-4633-8a9b-d78e9047afb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
