<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_propertyInfo</name>
   <tag></tag>
   <elementGuidId>35c314f2-f141-4c7a-99bf-eaecedf5ffb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-property-ad-retrieve/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.info.d-flex.mt-2.flex-column.justify-content-center.align-items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2031★ 4.9HVF7+3P Amora, PortugalPreviousNext&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aad15ce2-b8ac-49d7-b41d-fc0999d8fbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>info d-flex mt-2 flex-column justify-content-center align-items-center</value>
      <webElementGuid>e6b65bb9-1723-4395-8671-0a4e9c8d926f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2031★ 4.9HVF7+3P Amora, PortugalPreviousNext</value>
      <webElementGuid>c84174ba-eb1f-4e9b-809a-c1efd6cdef3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[1]/div[@class=&quot;container-fluid d-flex flex-grow-1&quot;]/app-property-ad-retrieve[1]/div[@class=&quot;main d-flex flex-column w-100&quot;]/div[@class=&quot;info d-flex mt-2 flex-column justify-content-center align-items-center&quot;]</value>
      <webElementGuid>3e564eed-af1e-4772-97b9-1e93c5b7fa09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar Sessão'])[1]/following::div[3]</value>
      <webElementGuid>0ac14d0e-1fb3-411e-b118-0bbec038e13e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registar'])[1]/following::div[3]</value>
      <webElementGuid>d29c6cbd-c202-4cd7-8b83-ed4637d552e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-property-ad-retrieve/div/div</value>
      <webElementGuid>b44bbb6b-1e37-47ce-817d-ea9d64c8943f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2031★ 4.9HVF7+3P Amora, PortugalPreviousNext' or . = '2031★ 4.9HVF7+3P Amora, PortugalPreviousNext')]</value>
      <webElementGuid>a5d34556-b756-427c-8002-19eded4ec2a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
