<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_firstProperty</name>
   <tag></tag>
   <elementGuidId>68947572-f5d9-4f73-8171-58e82b70dc5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-homepage-property/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-100.h-100.rounded-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>app-homepage-property >> internal:has-text=&quot;2031311331€ noitecompare_arrows&quot;i >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>032935ba-d089-4567-b52a-f8e1ae842e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 h-100 rounded-3</value>
      <webElementGuid>009bd5a0-1182-4fcc-b92c-0c041b940bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bookingbuddyrepository.blob.core.windows.net/images/a8dbb736-8ff1-4deb-8a12-a1917deb4f71.jpg</value>
      <webElementGuid>5d39378f-b36a-4ee8-bad8-ab622ecb960f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[1]/div[@class=&quot;container-fluid d-flex flex-grow-1&quot;]/app-homepage[1]/div[@class=&quot;d-flex p-3 w-100 flex-row flex-wrap align-content-start justify-content-start&quot;]/app-homepage-property[1]/div[@class=&quot;property d-flex flex-column p-3 w-100 h-100&quot;]/a[@class=&quot;w-100 h-75 m-1&quot;]/img[@class=&quot;w-100 h-100 rounded-3&quot;]</value>
      <webElementGuid>a06a28f7-5ed3-4f07-8652-7ccab7d739ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://bookingbuddyrepository.blob.core.windows.net/images/a8dbb736-8ff1-4deb-8a12-a1917deb4f71.jpg')]</value>
      <webElementGuid>e872ca64-113e-42ad-9adb-46c8df518315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-homepage-property/div/a/img</value>
      <webElementGuid>ca57862a-b002-4454-b3bd-5268b005e17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bookingbuddyrepository.blob.core.windows.net/images/a8dbb736-8ff1-4deb-8a12-a1917deb4f71.jpg']</value>
      <webElementGuid>18e7c6d2-51ef-4865-9b63-9bc91128698e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
