name: BookingBuddyServer and bookingbuddy.client - Build and Test

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  BookingBuddyServer-Build-Test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Install dependencies
        run: dotnet restore BookingBuddy/BookingBuddy.Server
      
      - name: Build BookingBuddy.Server
        run: dotnet build BookingBuddy/BookingBuddy.Server
      
      - name: Test BookingBuddyTest
        run: dotnet test BookingBuddy/BookingBuddyTest
  
  bookingbuddy-client-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Insatll dependencies
        working-directory: BookingBuddy/bookingbuddy.client
        run: npm install

      - name: Build bookingbuddy.client
        working-directory: BookingBuddy/bookingbuddy.client
        run: npm run build --if-present