name: Automatic Testing Workflow

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test-server:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0.x'
      
      - name: Test server
        run: dotnet test BookingBuddy/BookingBuddyServerTest -c Release
  
  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: BookingBuddy/bookingbuddy.client
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Node.js version
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'

      - name: Set up client environment
        run: >
            echo 
            '{
              "apiUrl": "${{ vars.API_URL }}",
              "googleClientId": "${{ secrets.GOOGLE_CLIENT_ID }}",
              "microsoftClientId": "${{ secrets.MICROSOFT_CLIENT_ID }}",
              "microsoftTenantId": "${{ secrets.MICROSOFT_TENANT_ID }}"
            }'
            > ./src/environments/environment.json
  
      - name: Install dependencies
        run: npm install

      - name: Build client
        run: npm run build --if-present